<?php

namespace Database\Seeders;

use App\Models\NewsSource;
use App\Services\Connectors\BcbSgsConnector;
use App\Services\Connectors\GenericJsonConnector;
use App\Services\Connectors\IbgeSidraConnector;
use App\Services\Connectors\RssConnector;
use Illuminate\Database\Seeder;

/**
 * Catalog of the 40 public-data sources discussed for the network. Only a
 * handful ship `is_active = true`: those are verified, key-free, working
 * endpoints demonstrating each connector type end to end (IBGE, BCB,
 * a CKAN search on dados.gov.br, NASA APOD). Every other row is a real
 * starting point but needs its endpoint/config confirmed (and often an API
 * key) before an operator flips it to active - see README "Fontes de
 * dados" for the checklist. This mirrors reality: 40 candidate sources
 * don't all have a stable, keyless, generic-JSON-shaped API.
 */
class NewsSourceSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->sources() as $source) {
            NewsSource::query()->updateOrCreate(
                ['key' => $source['key']],
                $source,
            );
        }
    }

    private function sources(): array
    {
        return [
            // --- Funcionais de fabrica (sem chave de API) ---------------------------------
            [
                'key' => 'ibge_sidra',
                'name' => 'IBGE - Sistema IBGE de Recuperacao Automatica (SIDRA)',
                'niches' => ['economia'],
                'connector' => IbgeSidraConnector::class,
                'endpoint' => null,
                'config' => ['tabela' => '1419', 'variavel' => '63', 'localidades' => 'N1[all]', 'periodos' => -3],
                'license_note' => 'Dados abertos IBGE - uso livre com atribuicao.',
                'is_active' => true,
            ],
            [
                'key' => 'bcb_sgs',
                'name' => 'Banco Central do Brasil - Sistema Gerenciador de Series Temporais (SGS)',
                'niches' => ['economia'],
                'connector' => BcbSgsConnector::class,
                'endpoint' => null,
                'config' => ['codigo_serie' => 433, 'ultimos' => 5],
                'license_note' => 'Dados abertos BCB. Troque codigo_serie para outra serie (ex: 432 = Selic meta, 1 = dolar PTAX).',
                'is_active' => true,
            ],
            [
                'key' => 'dados_gov_br',
                'name' => 'dados.gov.br - Portal Brasileiro de Dados Abertos (CKAN)',
                'niches' => ['economia', 'geral'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => 'https://dados.gov.br/api/3/action/package_search',
                'config' => [
                    'query' => ['q' => 'economia', 'rows' => 5],
                    'items_path' => 'result.results',
                    'id_field' => 'id',
                    'title_field' => 'title',
                    'summary_field' => 'notes',
                    'reference_url' => 'https://dados.gov.br',
                    'reference_title' => 'Portal Brasileiro de Dados Abertos',
                ],
                'license_note' => 'Catalogo CKAN publico - ajuste "q" para o termo de busca do nicho do site.',
                'is_active' => true,
            ],
            [
                'key' => 'nasa_apod',
                'name' => 'NASA Open APIs - Astronomy Picture of the Day',
                'niches' => ['ciencia'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => 'https://api.nasa.gov/planetary/apod',
                'config' => [
                    'query' => ['api_key' => 'DEMO_KEY', 'count' => 5],
                    'id_field' => 'date',
                    'title_field' => 'title',
                    'summary_field' => 'explanation',
                    'reference_title' => 'NASA',
                ],
                'license_note' => 'Dominio publico. DEMO_KEY tem limite baixo de requisicoes - gere uma chave gratuita em api.nasa.gov antes de ir para producao.',
                'is_active' => true,
            ],

            // --- APIs de dados oficiais (catalogo - configurar antes de ativar) -----------
            [
                'key' => 'tesouro_transparente',
                'name' => 'Tesouro Transparente',
                'niches' => ['economia'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => ['items_path' => null, 'id_field' => 'id', 'title_field' => 'title', 'summary_field' => 'summary'],
                'license_note' => 'Dados abertos - configurar endpoint especifico antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'cvm_dados_abertos',
                'name' => 'CVM - Dados Abertos',
                'niches' => ['economia'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos CVM - configurar endpoint/dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'anp_combustiveis',
                'name' => 'ANP - Precos de Combustiveis',
                'niches' => ['economia'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos ANP - configurar endpoint/regiao antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'tse_dados_abertos',
                'name' => 'TSE - Dados Abertos',
                'niches' => ['politica'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos TSE - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'inmet_clima',
                'name' => 'INMET - Dados Meteorologicos',
                'niches' => ['geral'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'API publica - exige codigo de estacao. Configurar antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'inpe_queimadas',
                'name' => 'INPE - BDQueimadas / Clima',
                'niches' => ['meio-ambiente'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos INPE - configurar endpoint antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'opendatasus',
                'name' => 'OpenDataSUS / Ministerio da Saude',
                'niches' => ['saude'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'world_bank',
                'name' => 'Banco Mundial - World Bank Open Data API',
                'niches' => ['economia', 'geral'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => 'https://api.worldbank.org/v2/country/BR/indicator/NY.GDP.MKTP.CD',
                'config' => ['query' => ['format' => 'json', 'per_page' => 5], 'items_path' => '1'],
                'license_note' => 'API publica, dominio publico. Itens nao tem campo "title" natural - GenericJsonConnector precisa de ajuste (ou conector dedicado) antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'imf_data',
                'name' => 'FMI - IMF Data API',
                'niches' => ['economia'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'API publica - configurar dataset/indicador antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'fred',
                'name' => 'FRED - Federal Reserve Economic Data',
                'niches' => ['economia'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => 'https://api.stlouisfed.org/fred/series/observations',
                'config' => ['query' => ['series_id' => 'CPIAUCSL', 'file_type' => 'json', 'api_key' => '']],
                'license_note' => 'Exige chave de API gratuita (fred.stlouisfed.org) - preencher config.query.api_key antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'eurostat',
                'name' => 'Eurostat',
                'niches' => ['economia'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'API publica - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'noaa_clima',
                'name' => 'NOAA - Clima e Oceanos',
                'niches' => ['meio-ambiente', 'ciencia'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Exige token de API (ncdc.noaa.gov/cdo-web/token) - configurar antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'who_data',
                'name' => 'WHO (OMS) Data API',
                'niches' => ['saude'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'API publica - configurar indicador antes de ativar.',
                'is_active' => false,
            ],

            // --- Comunicados oficiais com licenca aberta -----------------------------------
            [
                'key' => 'agencia_brasil_rss',
                'name' => 'Agencia Brasil (EBC)',
                'niches' => ['geral'],
                'connector' => RssConnector::class,
                'endpoint' => 'https://agenciabrasil.ebc.com.br/rss.xml',
                'config' => [],
                'license_note' => 'Creative Commons (permite adaptacao com credito) - confirme a URL do feed antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'notas_oficiais_rss',
                'name' => 'Notas oficiais via RSS (BCB, ministerios, prefeituras)',
                'niches' => ['geral'],
                'connector' => RssConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Comunicado institucional, nao reportagem de terceiros - configurar URL do feed do orgao antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'data_europa_eu',
                'name' => 'data.europa.eu',
                'niches' => ['economia', 'geral'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Portal de dados abertos da UE - configurar dataset antes de ativar.',
                'is_active' => false,
            ],

            // --- Mais fontes brasileiras setoriais (catalogo) ------------------------------
            [
                'key' => 'receita_federal',
                'name' => 'Receita Federal - Dados Abertos',
                'niches' => ['economia'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'novo_caged',
                'name' => 'Novo CAGED (Ministerio do Trabalho)',
                'niches' => ['trabalho', 'economia'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'inep_educacao',
                'name' => 'INEP - Censo Escolar / ENEM / IDEB',
                'niches' => ['educacao'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'cnj_datajud',
                'name' => 'CNJ - Justica em Numeros / DataJud',
                'niches' => ['justica'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Exige credenciais de acesso ao DataJud - configurar antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'portal_transparencia',
                'name' => 'Portal da Transparencia (CGU)',
                'niches' => ['politica', 'economia'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => 'https://api.portaldatransparencia.gov.br/api-de-dados/despesas/por-orgao',
                'config' => ['query' => ['mesAno' => null, 'pagina' => 1]],
                'license_note' => 'Exige header "chave-api-dados" (cadastro gratuito) - configurar antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'aneel_energia',
                'name' => 'ANEEL - Tarifas e Dados do Setor Eletrico',
                'niches' => ['energia'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'anatel_telecom',
                'name' => 'ANATEL - Telecomunicacoes',
                'niches' => ['tecnologia'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'anvisa_saude',
                'name' => 'ANVISA - Medicamentos e Vigilancia Sanitaria',
                'niches' => ['saude'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'ans_planos_saude',
                'name' => 'ANS - Planos de Saude',
                'niches' => ['saude'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'antt_transporte',
                'name' => 'ANTT - Transporte Rodoviario/Ferroviario',
                'niches' => ['transporte'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'anac_aviacao',
                'name' => 'ANAC - Voos, Atrasos e Malha Aerea',
                'niches' => ['transporte'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'ibama_ambiental',
                'name' => 'IBAMA - Autuacoes e Licenciamento Ambiental',
                'niches' => ['meio-ambiente'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'icmbio_biodiversidade',
                'name' => 'ICMBio - Biodiversidade e Unidades de Conservacao',
                'niches' => ['meio-ambiente'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'datasus_tabnet',
                'name' => 'DataSUS / TabNet',
                'niches' => ['saude'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'infogripe_fiocruz',
                'name' => 'InfoGripe (Fiocruz)',
                'niches' => ['saude'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados publicos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'camara_dados_abertos',
                'name' => 'Camara dos Deputados - Dados Abertos',
                'niches' => ['politica'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => 'https://dadosabertos.camara.leg.br/api/v2/proposicoes',
                'config' => ['query' => ['itens' => 5, 'ordem' => 'DESC', 'ordenarPor' => 'id'], 'items_path' => 'dados'],
                'license_note' => 'API publica estavel, mas os itens nao tem um campo de titulo unico - recomendado escrever um conector dedicado antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'senado_dados_abertos',
                'name' => 'Senado Federal - Dados Abertos',
                'niches' => ['politica'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'API publica - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'b3_mercado',
                'name' => 'B3 - Dados Historicos de Mercado',
                'niches' => ['economia'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados publicos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'portais_dados_municipais',
                'name' => 'Portais estaduais/municipais de dados abertos',
                'niches' => ['geral'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'CKAN por cidade/estado (ex: dados.rio, dados.prefeitura.sp.gov.br) - configurar por site antes de ativar.',
                'is_active' => false,
            ],
            [
                'key' => 'susep_seguros',
                'name' => 'SUSEP - Mercado de Seguros',
                'niches' => ['economia'],
                'connector' => GenericJsonConnector::class,
                'endpoint' => null,
                'config' => [],
                'license_note' => 'Dados abertos - configurar dataset antes de ativar.',
                'is_active' => false,
            ],
        ];
    }
}
